config/routes.rb
Caloriemate::Application.routes.draw do
  
  resources :foods

  resources :days

  
  root :to => 'welcome#index'

  

end

app/models/day.rb
class Day < ActiveRecord::Base
   attr_accessible :id, :total_calories, :total_protien, 
   :total_carbs, :total_fat
   
  has_many :menus

  accepts_nested_attributes_for :menus
  
  has_many :foods, through: :menus

  def total_calories
  	day = self
  	total_calories = day.foods.sum(:calories)
  end

  def total_protien
  	day = self
  	total_protien = day.foods.sum(:protien)
  end

  def total_carbs
  	day = self
  	total_carbs = day.foods.sum(:carbs)
  end

  def total_fat
  	day = self
  	total_carbs = day.foods.sum(:fat)
  end

end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :calories, :carbs, :fat, :name, :protien, :id

  has_many :menus

  accepts_nested_attributes_for :menus

  has_many :days, through: :menus

  def name_for_select
  	name.capitalize
  end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
   attr_accessible :id, :food_id, :day_id
  
  belongs_to :food
  belongs_to :day
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/days_controller.rb
class DaysController < ApplicationController

	def index
		@days = Day.all
	end

	def new
		@day = Day.new
		@menu = Menu.new
	end

def create
		@day = Day.new(params[:day])
		@day.save

		@menu = Menu.new(params[:menu])
		@menu.day_id =  @day.id
		@menu.save
		

		redirect_to @day
	end
	
	
	def show
		@day = Day.find(params[:id])
	end

	def edit
		@day = Day.find(params[:id])
	end

	def update
		@day = Day.find(params[:id])

		@menu = Menu.new(params[:menu])
		@menu.day_id = @day.id
		@menu.save

		redirect_to @day
	end

	def destroy
		@day = Day.find(params[:id])
		@day.destroy

		redirect_to @day
	end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

	def index
		@foods = Food.all
	end

	def new
	end

	def create 
		@food = Food.new(params[:food])

		@food.save
		redirect_to @food
	end

	def show
		@food = Food.find(params[:id])
	end

	def edit
		@food = Food.find(params[:id])
	end

	def update
		@food = Food.find(params[:id])

		if @food.update_attributes(params[:food])
			redirect_to @food
		else
			render 'edit'
		end
	end

	def destroy
		@food = Food.find(params[:id])
		@food.destroy

		redirect_to @food
	end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

	#def new
	#	@menu = Menu.new
	#end

	#def create
		#binding.pry
	#	@menu = Menu.new(params[:menu])

	#	@menu.save
	#	redirect_to @day
	#end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/days/edit.html.erb
<div class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" <%= link_to 'Calorie Mate', controller: 'welcome' %> >Calorie Mate</a>
		</div>
		<div>
			<ul class="nav navbar-nav navbar-right">
				<li> <%= link_to 'Home', controller: 'welcome' %></li>
				<li><%= link_to 'Log', controller: 'days'%></li>
				<li><%= link_to 'Menu', controller: 'foods' %></li>
			</ul>
		</div>
	</div>
</div>

<div class="container">
	<h1>Add another food for today </h1>
</div>

<div class="container">
	<%= form_for :menu, url: day_path(@day), method: :put do |m| %>
	<%= m.collection_select(:food_id, Food.all, :id, :name_for_select) %>
</div>
<div class= "container">
	<%= m.submit "Submit", class: "btn-btn-info" %>
	<% end %>
</div>

app/views/days/index.html.erb
<div class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" <%= link_to 'Calorie Mate', controller: 'welcome' %> >Calorie Mate</a>
		</div>
		<div>
			<ul class="nav navbar-nav navbar-right">
				<li> <%= link_to 'Home', controller: 'welcome' %></li>
				<li><%= link_to 'Log', controller: 'days'%></li>
				<li><%= link_to 'Menu', controller: 'foods' %></li>
			</ul>
		</div>
	</div>
</div>

<div class="container">
	<table class="table table-striped">
		<thead>
			<th>Date</th>
			<th>Total Calories</th>
			<th>Total Proiten</th>
			<th>Total Carbs</th>
			<th>Total Fat</th>
			<th clospan="3"></th>
		</thead>
		<tbody>
			<% @days.each do |d| %>
		<tr>
			<td><%= d.id %></td>
			<td><%= d.total_calories %></td>
			<td><%= d.total_protien %></td>
			<td><%= d.total_carbs %></td>
			<td><%= d.total_fat %></td>
			<td><%= link_to 'View', day_path(d)%></td>
			<td><%= link_to 'Edit', edit_day_path(d) %></td>
			<td><%= link_to 'Destroy', day_path(d), 
				method: :delete, data: { confirm: 'Are you sure?'} %>
			</td>
		</tr>
		</tbody>
		<% end %>
	</table>
</div>

<div class="container">
<%= link_to 'Home', controller: 'welcome' %>
</div>

app/views/days/new.html.erb
<div class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" <%= link_to 'Calorie Mate', controller: 'welcome' %> >Calorie Mate</a>
		</div>
		<div>
			<ul class="nav navbar-nav navbar-right">
				<li> <%= link_to 'Home', controller: 'welcome' %></li>
				<li><%= link_to 'Log', controller: 'days'%></li>
				<li><%= link_to 'Menu', controller: 'foods' %></li>
			</ul>
		</div>
	</div>
</div>

<div class="container">
	<h1>New Day</h1>
</div>

<div class="container">
	<h3>Add a Food</h3>
	<%#= form_for @day do |f| %>
	<%= form_for :menu, url: days_path do |m| %>
	<%= m.collection_select(:food_id, Food.all, :id, :name_for_select) %>
	<%# end %>
</div>
<div class="container">
	<%= m.submit "Submit", class: "btn-btn-info" %>
	<% end %>
</div>

app/views/days/show.html.erb
<div class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" <%= link_to 'Calorie Mate', controller: 'welcome' %> >Calorie Mate</a>
		</div>
		<div>
			<ul class="nav navbar-nav navbar-right">
				<li> <%= link_to 'Home', controller: 'welcome' %></li>
				<li><%= link_to 'Log', controller: 'days'%></a></li>
				<li><%= link_to 'Menu', controller: 'foods' %></li>
			</ul>
		</div>
	</div>
</div>

<div class="container">
	<%#= Need to change the Day ID below to a Date %>
	<h1>Day <%= @day.id %></h1><br>
	<h3> Eaten: </h3>
	<div class="container">
		<table class="table table-striped">
			<thead>
				<th>Food</th>
				<th>Calories</th>
				<th>Protien</th>
				<th>Carbs</th>
				<th>Fat</th>
				<th colspan = "2"></th>
			</thead>
			<tbody>
				<% @day.foods.each do |f| %>
				<tr>
					<td><%= f.name %></td>
					<td><%= f.calories %></td>
					<td><%= f.protien %></td>
					<td><%= f.carbs %></td>
					<td><%= f.fat %></td>
					<td colspan="2"></td>
				</tr>
			</tbody>
			<% end %>
		</table>
	</div>
<div class="container">
	<table class="table table-bordered">
		<thead>
			<th><strong>Total Calories</strong> </th>
			<th><strong>Total Protien</strong></th>
			<th><strong>Total Carbs</strong></th>
			<th><strong>Total Fat</strong></th>
		</thead>
		<tbody>
			<td><%= @day.total_calories %> </td>
			<td><%= @day.total_protien %></td>
			<td><%= @day.total_carbs %></td>
			<td><%= @day.total_fat %></td>
		</tbody>
	</table>
</div>

<div class="btn btn-primary">
	Add Food
<%= link_to 'Add a Food', edit_day_path %>
</div>

<div class="btn btn-primary">
	Save Day
<%= link_to 'Index', days_path %>
</div>

app/views/foods/edit.html.erb
<div class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" <%= link_to 'Calorie Mate', controller: 'welcome' %> >Calorie Mate</a>
		</div>
		<div>
			<ul class="nav navbar-nav navbar-right">
				<li> <%= link_to 'Home', controller: 'welcome' %></li>
				<li><%= link_to 'Log', controller: 'days'%></li>
				<li><%= link_to 'Menu', controller: 'foods' %></li>
			</ul>
		</div>
	</div>
</div>

<div class="container">
	<h1> Edit Food </h1>
</div>

<div class="container">
	<%= form_for :food, url: food_path(@food), method: :put do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %> <br>
		<%= f.label :calories %><br>
		<%= f.text_field :calories %><br>
		<%= f.label :protien %><br>
		<%= f.text_field :protien %><br>
		<%= f.label :carbs %><br>
		<%= f.text_field :carbs %><br>
		<%= f.label :fat %><br>
		<%= f.text_field :fat %><br>
	</p>
	<p>
		<%= f.submit %>
	</p>
	<% end %>
	<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<div class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" <%= link_to 'Calorie Mate', controller: 'welcome' %> >Calorie Mate</a>
		</div>
		<div>
			<ul class="nav navbar-nav navbar-right">
				<li> <%= link_to 'Home', controller: 'welcome' %></li>
				<li><%= link_to 'Log', controller: 'days'%></li>
				<li><%= link_to 'Menu', controller: 'foods' %></li>
			</ul>
		</div>
	</div>
</div>

<div class="container">
	<h1> All Foods </h1>
</div>

<div class="container">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Food</th>
				<th>Calories</th>
				<th>Protien</th>
				<th>Carbs</th>
				<th>Fat</th>
				<th colspan="2"></th>
			</tr>
		</thead>
		<tbody>
			<% @foods.each do |f| %>
			<tr>
				<td><%= f.name %></td>
				<td><%= f.calories %></td>
				<td><%= f.protien %></td>
				<td><%=f.carbs %></td>
				<td><%=f.fat %></td>
				<td><%= link_to 'Edit', edit_food_path(f) %></td>
				<td><%= link_to 'Destroy', food_path(f), 
					method: :delete, data: { confirm: 'Are you sure?'} %></td>
			</tr>
		</tbody>
		<% end %>
	</table>
</div>


<div class="container">
	<a href=/foods/new class="btn btn-primary" role="button">New Food</a>
</div>

app/views/foods/new.html.erb
<div class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" <%= link_to 'Calorie Mate', controller: 'welcome' %> >Calorie Mate</a>
		</div>
		<div>
			<ul class="nav navbar-nav navbar-right">
				<li> <%= link_to 'Home', controller: 'welcome' %></li>
				<li><%= link_to 'Log', controller: 'days'%></li>
				<li><%= link_to 'Menu', controller: 'foods' %></li>
			</ul>
		</div>
	</div>
</div>

<div class="container">
	<h1>Add New Food</h1>
</div>
<div class="container">
	<%= form_for :food, url: foods_path do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>
		<%= f.label :calories %><br>
		<%= f.text_field :calories %><br>
		<%= f.label :protien %><br>
		<%= f.text_field :protien %><br>
		<%= f.label :carbs %><br>
		<%= f.text_field :carbs %><br>
		<%= f.label :fat %><br>
		<%= f.text_field :fat %><br>
	</p>
	<p>
	<%= f.submit %>
	</p>
	<% end %>
</div>

app/views/foods/show.html.erb
<div class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" <%= link_to 'Calorie Mate', controller: 'welcome' %> >Calorie Mate</a>
		</div>
		<div>
			<ul class="nav navbar-nav navbar-right">
				<li> <%= link_to 'Home', controller: 'welcome' %></li>
				<li><%= link_to 'Log', controller: 'days'%></li>
				<li><%= link_to 'Menu', controller: 'foods' %></li>
			</ul>
		</div>
	</div>
</div>

<div class="container">
	<h1>
	<%= @food.name %>
	</h1>
<p><strong>Calories  </strong><%= @food.calories %></p>
<p><strong>Protien  </strong> <%= @food.protien %></p>
<p><strong>Carbs  </strong><%= @food.carbs %></p>
<p><strong>Fat  </strong><%= @food.fat %></p>
</div>

<div class="container">
	<%= link_to 'All Foods', controller: 'foods' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Caloriemate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
	<div class="jumbotron">
		<h1> Calorie Mate</h1>
		<p> Track what you eat</p>
	</div>
</div>

<div class="container">
	<a href=/days/new class="btn btn-primary" role="button">New Day</a>
	<a href=/days class="btn btn-primary" role="button">Log</a>
	<a href=/foods class="btn btn-primary" role="button">Menu</a>
</div>